/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketplaceSol from './Marketplace.sol/index.js';
export type { marketplaceSol };
import type * as nftSol from './NFT.sol/index.js';
export type { nftSol };
export * as factories from './factories/index.js';
export type { NFTMarketplace } from './Marketplace.sol/NFTMarketplace.js';
export { NFTMarketplace__factory } from './factories/Marketplace.sol/NFTMarketplace__factory.js';
export type { BODOINFT } from './NFT.sol/BODOINFT.js';
export { BODOINFT__factory } from './factories/NFT.sol/BODOINFT__factory.js';